//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class DroneTrajectoryMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/DroneTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg[] positions;

        public DroneTrajectoryMsg()
        {
            this.positions = new Geometry.PointMsg[0];
        }

        public DroneTrajectoryMsg(Geometry.PointMsg[] positions)
        {
            this.positions = positions;
        }

        public static DroneTrajectoryMsg Deserialize(MessageDeserializer deserializer) => new DroneTrajectoryMsg(deserializer);

        private DroneTrajectoryMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.positions, Geometry.PointMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.positions);
            serializer.Write(this.positions);
        }

        public override string ToString()
        {
            return "DroneTrajectoryMsg: " +
            "\npositions: " + System.String.Join(", ", positions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
