//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class MeasurementPacketMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/MeasurementPacket";
        public override string RosMessageName => k_RosMessageName;

        public MeasurementPointMsg[] points;

        public MeasurementPacketMsg()
        {
            this.points = new MeasurementPointMsg[0];
        }

        public MeasurementPacketMsg(MeasurementPointMsg[] points)
        {
            this.points = points;
        }

        public static MeasurementPacketMsg Deserialize(MessageDeserializer deserializer) => new MeasurementPacketMsg(deserializer);

        private MeasurementPacketMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.points, MeasurementPointMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.points);
            serializer.Write(this.points);
        }

        public override string ToString()
        {
            return "MeasurementPacketMsg: " +
            "\npoints: " + System.String.Join(", ", points.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
